site_name: PHN Exchange Help Centre
site_url: https://www.phnexchange.com.au/
site_description: PHN Exchange Help Centre

theme:
        name: "material"
        logo: "images/icon.png"

site_dir: docs/
docs_dir: src/

nav:
        - Home: "index.md"
        - General Practices:
                  - Introduction: "practices/introduction.md"
                  - Practice Profile: "practices/profile.md"
                  - Data Report: "practices/data-report.md"
                  - Licensing and Agreements: "practices/licensing-agreements.md"
        - Partner PHNs:
                  - Introduction: "phns/introduction.md"
                  - PHN Admin:
                        - Introduction: "phns/phn-admins/introduction.md"
                        - Reports: "phns/phn-admins/reports.md"
                        - Practice Datasource: "phns/phn-admins/practice-datasource.md"
                        - Practices: "phns/phn-admins/practices.md"
                        - Priority Areas: "phns/phn-admins/priority-areas.md"
                        - Regions: "phns/phn-admins/regions.md"
                        - Licenses: "phns/phn-admins/licenses.md"
                        - PHN Members: "phns/phn-admins/phn-members.md"
                  - Cyber Security and Data Governance: "phns/security.md"
                  - Regulations: "phns/regulations.md"
                  - EULA: "phns/eula.md"
                  - PIP QI: "phns/pipqi.md"
                  - System Specifications: "phns/system-specifications.md"
                  - Engagement with Practices: "phns/engagement.md"
                  - Population Health Principles: "phns/populationhealth.md"
                  - Components:
                            - Priority Areas: "phns/components/priority-areas.md"
                            - GP Data: "phns/components/gpdata.md"
                            - ABS Atlas: "phns/components/atlas.md"
                            - Learning Management System: "phns/components/lms.md"
                            - Data Extraction: "phns/components/extraction.md"
                  - Resources: "phns/resources.md"
                  - Support: "phns/support.md"
        - Members: "members.md"
        - Terms and Conditions: "terms.md"
        - Privacy Policy: "privacy.md"
        - Changelog: "changelog.md"

extra_css:
        - ../css/extra.css

markdown_extensions:
        - toc:
                permalink: true
